import { motion } from 'framer-motion';
import { ArrowRight, Terminal, Zap, Shield } from 'lucide-react';

export default function Hero() {
  return (
    <section className="relative min-h-screen flex items-center pt-20 overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0 z-0">
        <div className="absolute top-20 left-1/4 w-96 h-96 bg-blue-500/20 rounded-full blur-3xl" />
        <div className="absolute bottom-20 right-1/4 w-96 h-96 bg-cyan-500/20 rounded-full blur-3xl" />
      </div>

      <div className="container relative z-10 grid lg:grid-cols-2 gap-12 items-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-sm font-medium mb-6">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
            v0.0.4 is now available
          </div>

          <h1 className="text-5xl lg:text-7xl font-bold leading-tight mb-6">
            Automate Your <br />
            <span className="text-gradient">Frontend API Coding</span>
          </h1>

          <p className="text-lg text-secondary mb-8 max-w-xl">
            Stop writing manual API requests. UnoAPI generates type-safe TypeScript code directly from your OpenAPI specs.
          </p>

          <div className="flex flex-wrap gap-4">
            <a href="#get-started" className="btn-primary flex items-center gap-2">
              Get Started <ArrowRight size={18} />
            </a>
            <a href="https://github.com/moohng/unoapi" className="btn-secondary flex items-center gap-2">
              <Terminal size={18} /> View on GitHub
            </a>
          </div>

          <div className="mt-12 flex items-center gap-8 text-sm text-secondary">
            <div className="flex items-center gap-2">
              <Zap size={16} className="text-yellow-400" />
              <span>Instant Generation</span>
            </div>
            <div className="flex items-center gap-2">
              <Shield size={16} className="text-green-400" />
              <span>100% Type Safe</span>
            </div>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="relative"
        >
          <div className="relative rounded-xl overflow-hidden border border-white/10 shadow-2xl bg-[#1e1e1e]">
            <div className="flex items-center gap-2 px-4 py-3 border-b border-white/5 bg-[#252526]">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-[#ff5f56]" />
                <div className="w-3 h-3 rounded-full bg-[#ffbd2e]" />
                <div className="w-3 h-3 rounded-full bg-[#27c93f]" />
              </div>
              <div className="ml-4 text-xs text-gray-400 font-mono">api.ts</div>
            </div>
            <div className="p-6 font-mono text-sm overflow-x-auto">
              <div className="text-gray-400">// Generated by UnoAPI</div>
              <div className="mt-2">
                <span className="text-purple-400">export</span> <span className="text-blue-400">async function</span> <span className="text-yellow-400">getUser</span>(id: <span className="text-green-400">number</span>) {'{'}
              </div>
              <div className="pl-4">
                <span className="text-purple-400">return</span> <span className="text-blue-400">request</span>.{'get<'}<span className="text-green-400">User</span>{'>'}(<span className="text-orange-400">`/users/${'{'}id{'}'}`</span>);
              </div>
              <div>{'}'}</div>

              <div className="mt-4 text-gray-400">// Type Definition</div>
              <div>
                <span className="text-purple-400">export interface</span> <span className="text-green-400">User</span> {'{'}
              </div>
              <div className="pl-4">
                id: <span className="text-green-400">number</span>;
              </div>
              <div className="pl-4">
                name: <span className="text-green-400">string</span>;
              </div>
              <div className="pl-4">
                email: <span className="text-green-400">string</span>;
              </div>
              <div>{'}'}</div>
            </div>
          </div>

          {/* Floating Badge */}
          <motion.div
            animate={{ y: [0, -10, 0] }}
            transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
            className="absolute -top-6 -right-6 glass p-4 rounded-xl border border-white/10 shadow-xl"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center text-blue-400">
                <Terminal size={20} />
              </div>
              <div>
                <div className="text-xs text-secondary">Supported Specs</div>
                <div className="font-bold">OpenAPI 3.0+</div>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
}
